[tool.poetry]
name = "cleanup"
version = "0.1.0"
description = ""
authors = ["Logan Donley <ldonley@cloudbees.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
